# Generated by Django 5.2.5 on 2025-09-14 18:17

import apps.profiles.models
import django.core.validators
import utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.upload_to, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'gif', 'webp')), utils.files.validate_file_size]),
        ),
    ]
