# Generated by Django 5.2.5 on 2025-09-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_verification_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_verification_email_sent',
            new_name='last_activation_email_sent',
        ),
    ]
