# Generated by Django 5.2.5 on 2025-09-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_last_verification_email_sent_user_last_activation_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verified',
            new_name='account_activated',
        ),
    ]
