# Generated by Django 5.2.5 on 2025-10-07 13:25

import apps.stories.models
import django.core.validators
import django.db.models.deletion
import utils.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=apps.stories.models.upload_to, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'gif', 'webp', 'jpg', 'jpeg', 'png', 'gif', 'webp')), utils.files.validate_file_size])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.stories.models.set_expiry_datetime)),
                ('public_id', models.CharField(default=apps.stories.models.generate_public_id, max_length=22, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ('-created',),
            },
        ),
    ]
