# Generated by Django 5.2.5 on 2025-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=5),
        ),
    ]
