# Generated by Django 5.2.5 on 2025-10-19 14:20

import apps.stories.models
import django.core.validators
import utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_media_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=5),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.stories.models.collection_upload_to, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'gif', 'webp')), utils.files.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='collections', to='stories.story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=10),
        ),
    ]
