# Generated by Django 5.2.5 on 2025-11-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_media_type_alter_collection_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='owner',
            new_name='author',
        ),
    ]
