# Generated by Django 5.2.5 on 2025-12-01 19:20

import apps.stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_rename_owner_collection_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=apps.stories.models.set_expiry_datetime, null=True),
        ),
    ]
