# Generated by Django 5.2.5 on 2025-10-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_story_alter_message_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('post', 'Post'), ('story', 'Story'), ('story_reply', 'StoryReply')], default='text', max_length=15),
        ),
    ]
